Add playlists
gualter-p/my-movies-app pull request #3
Opened 2024-11-12 08:55 UTC by gualter-p

- Adds My Movies page, where the user playlists are shown
- User is now able to select a movie and add it to an existing playlist, or add it to a newly created one

2024-11-12 15:59 UTC, gnribeiro requested changes

2024-11-12 15:59 UTC, gnribeiro commented on screens/MyMovies.tsx
> +
remove console.logs

2024-11-13 09:09 UTC, gnribeiro approved these changes

2024-11-14 15:51 UTC, luisplduarte approved these changes

2024-11-28 16:12 UTC, merged